version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: django_db
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py populate_products && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data: